### ISSUE TITLE
Is it possible to use this with standard US Letter sized paper?

### ISSUE THREAD

**Issue by PetSven** [dfd-tud/deda#14]
I want to anonymise a document for printing. However, I noticed the testpage.pdf is using the A4/ISO 216 paper size. If I try to print it, it will be printed at a reduced size because it is a different aspect ratio. Is it possible to use this program with standard US Letter sized paper?

**Comment by timojuez** [comment]
Hi Peter,

good news. Not only the calibration page but also the anonymised pages
shall also be put into A4 format automatically by the program. Therefore,
the anonymisation mask will always fit. No matter what transformation your
printer adds.
Also you can change the format in privacy.py. Make sure that you create a
fresh calibration page (deda_anonmask_create -w) and always use the same
format for anonymising as for the calibration page. Although in our lab the
anonymisation has worked, please verify the correct position of the mask on
the paper using a microscope or do not rely on the anonymisation 100%
otherwise.


Best wishes,

Timo


Am Do., 5. Sept. 2019 um 16:29 Uhr schrieb Peter Svendsen <
notifications@github.com>:
